import { SKILL_DATABASE } from '../monsterData';
import { MONSTER_TRAITS } from '../data/monsterTraits';

export const LANGUAGE_STORAGE_KEY = 'pixel_monster_language';

export const LANGUAGES = {
    zh: 'zh',
    en: 'en',
};

const EXACT_TRANSLATIONS = {
    '像素怪獸\n按A開始冒險': 'PIXEL MONSTER\nPress A to start',
    '無資料': 'No data',
    '時間讀取失敗': 'Failed to read time',
    '今日尚無重大事件': 'No major event today',
    '保持現狀也很不錯。': 'Keeping things as they are is fine too.',
    '準備出發冒險...': 'Getting ready for adventure...',
    '正在森林中探索...': 'Exploring the forest...',
    '🚩 冒險已結束，按 [B] 返回': 'Adventure complete. Press [B] to return.',
    '冒險結束。': 'Adventure complete.',
    '💀 戰敗撤退中... 需要多吃點飯糰了': 'Defeated and retreating... eat more rice balls next time.',
    '💨 逃跑成功...': 'Escaped successfully...',
    '吼吼吼～': 'Roooaaar...',
    '家裡來了一隻小像素怪獸...': 'A little pixel monster came home...',
    '主人歡迎回來~': 'Welcome back, trainer.',
    '餵食': 'Feed',
    '撫摸': 'Pet',
    '結束互動': 'End Care',
    '結束互動。': 'Care ended.',
    '尚未裝備技能！': 'No skill equipped.',
    '該格子尚未裝備技能！': 'No skill equipped in this slot.',
    '尚未解鎖此怪獸的詳細資訊...': 'Detailed info for this monster is not unlocked yet...',
    '抓到你了！': 'Got you!',
    '對戰中無法逃跑！': 'You cannot flee during battle.',
    '無法返回！': 'Cannot go back.',
    '請點按 B 鍵讀完日誌！': 'Press B to finish reading the log.',
    '冒險中請遵循路徑！': 'Follow the path during adventure.',
    '連線已中斷': 'Connection lost.',
    '正在連線中...': 'Connecting...',
    '連線逾時': 'Connection timed out.',
    '請先輸入房號': 'Enter a room code first.',
    'PeerJS 發生錯誤': 'PeerJS error occurred.',
    '對手加入逾時': 'Opponent join timed out.',
    '無法建立對戰房間': 'Unable to create battle room.',
    '網路連線錯誤': 'Network connection error.',
    '對手不可用': 'Opponent unavailable.',
    '等待對手出招...': 'Waiting for opponent move...',
    '招式已送出，等待判定...': 'Move submitted. Waiting for result...',
    '🏆 戰鬥勝利！': 'Battle won!',
    '💀 戰體力耗盡...': 'HP depleted...',
    '特訓失敗。': 'Training failed.',
    '目前無法讀取 Firebase 排行榜資料。': 'Unable to read Firebase leaderboard data.',
    '排行榜資料讀取失敗，請稍後再試。': 'Failed to read leaderboard. Try again later.',
    '需要將寵物培育至 Stage 2 以上才能報名大賽！': 'Raise your pet to Stage 2 or higher before entering the tournament.',
    '附魔已滿：身上四個技能都不能附魔。輔助技能無法附魔，攻擊技能最高只能到 10/10 MAX。': 'Enchantments are full: none of the four skills can be enchanted. Support skills cannot be enchanted, and attack skills max out at 10/10.',
    '【大會廣播】：當前戰鬥開始！': 'Tournament broadcast: Battle begins!',
    '進化條件': 'Evolution Requirements',
    '進化方向：': 'Evolution Path:',
    '已經是最終狀態': 'Already at final form',
    '無特殊條件': 'No special requirements',
    '無條件進化': 'Evolves without extra requirements',
    '其餘條件': 'Other requirements',
    '透過談心選擇進入不同屬性路線': 'Choose different elemental routes through Heart Talk',
    '透過互動進入不同支線': 'Enter different branches through Care',
    '透過冒險機率觸發': 'May trigger through Adventure',
    '【靈魂線】透過談心選擇進入不同屬性路線': '[Soul Line] Choose different elemental routes through Heart Talk',
    '【一般線】透過互動進入不同支線': '[Normal Line] Enter different branches through Care',
    '【野外線】透過冒險機率觸發': '[Wild Line] May trigger through Adventure',
    '心情、飽食度 >= 50': 'Mood and Fullness >= 50',
    '火系靈魂': 'Fire Soul',
    '水系靈魂': 'Water Soul',
    '草系靈魂': 'Grass Soul',
    '蟲系靈魂': 'Bug Soul',
    '一般線 A': 'Normal Line A',
    '一般線 C': 'Normal Line C',
    '靈魂線': 'Soul Line',
    '一般線': 'Normal Line',
    '野外線': 'Wild Line',
    '像素怪獸圖鑑': 'Pixel Monster Dex',
    '[A] 切換 [B] 詳細': '[A] Switch  [B] Details',
    '按 [B] 或 [C] 返回': 'Press [B] or [C] to return',
    '已收錄於怪獸圖鑑': 'Registered in the Monster Dex',
    '活力飯糰': 'Energy Rice Ball',
    '戰鬥蛋白粉': 'Battle Protein',
    '覺醒之核': 'Awakening Core',
    '奇異糖果': 'Rare Candy',
    '堅硬秘笈書': 'Harden Manual',
    '影子分身術秘笈書': 'Shadow Clone Manual',
    '戰舞秘笈書': 'Battle Dance Manual',
    '十字防守秘笈書': 'Cross Defense Manual',
    '反射盾秘笈書': 'Reflect Shield Manual',
    '守護者之盾秘笈書': 'Guardian Shield Manual',
    '技能轉換器': 'Skill Converter',
    '個體值提升劑': 'IV Booster',
    '回憶膠囊': 'Memory Capsule',
    '📖 對戰日記': 'Battle Diary',
    '永久提升基礎戰力 10 點': 'Permanently raises base power by 10.',
    '提升 10 點攻擊力與戰力': 'Raises Attack and Power by 10.',
    '提升基礎戰力與全屬性': 'Raises base power and all stats.',
    '隨機大幅提升戰鬥屬性': 'Greatly raises a random battle stat.',
    '讓怪獸學會招式「堅硬防守」(防禦+2)': 'Teaches the move Harden (+2 Defense).',
    '讓怪獸學會招式「影子分身術」(速度+2)': 'Teaches the move Shadow Clone (+2 Speed).',
    '讓怪獸學會招式「戰舞」(攻擊+2)': 'Teaches the move Battle Dance (+2 Attack).',
    '讓怪獸學會招式「十字防守」(該回合免疫攻擊，連續使用命中減半)': 'Teaches Cross Defense (immune to attacks this turn; repeated use halves accuracy).',
    '讓怪獸學會招式「反射盾」(受到傷害時反射 25% 傷害)': 'Teaches Reflect Shield (reflects 25% damage when hit).',
    '讓怪獸學會招式「守護者之盾」(施放後獲得 30% 最大生命值的護盾)': 'Teaches Guardian Shield (grants a shield equal to 30% max HP).',
    '可隨意調整 4 招技能的順序。限滿 4 招時使用。': 'Lets you freely reorder 4 skills. Usable only when all 4 slots are filled.',
    '隨機提升一項個體值評級 (例如 A -> S)。': 'Randomly raises one IV grade (for example A -> S).',
    '儲存了過往同伴的回憶，使用後可讓該怪獸重生。': 'Stores memories of a past partner. Use it to revive that monster.',
    '記錄每日的冒險與成長足跡。': 'Records daily adventures and growth.',
    '系統設定': 'System Settings',
    '畫面尺寸': 'Display Size',
    '自動': 'Auto',
    '小': 'Small',
    '中': 'Medium',
    '大': 'Large',
    '特大': 'XL',
    '標準': 'Standard',
    '中尺寸': 'Medium',
    '大尺寸': 'Large',
    '小 / 中 / 大': 'Small / Medium / Large',
    '320×620 起': '320x620+',
    '語言': 'Language',
    '中文': 'Chinese',
    '英文': 'English',
    '死亡引導': 'Defeat Guide',
    '每日信件': 'Daily Letters',
    '遊戲音效': 'Sound Effects',
    '背景音樂': 'Music',
    '音量': 'Volume',
    '開啟': 'On',
    '關閉': 'Off',
    '返回登入畫面': 'Return to Login',
    '清除遊戲存檔': 'Clear Save Data',
    '再點擊一次以確定清除 (無法復原)': 'Click Again to Confirm (Cannot Undo)',
    '離開遊戲': 'Exit Game',
    '關閉設定': 'Close Settings',
    '雲端同步中...': 'Cloud syncing...',
    '雲端存檔選擇': 'Cloud Save Choice',
    '匯入雲端進度': 'Import Cloud Progress',
    '用本機覆蓋雲端': 'Overwrite Cloud with Local',
    '建立雲端備份': 'Create Cloud Backup',
    '稍後決定': 'Decide Later',
    '同步中...': 'Syncing...',
    '雲端存檔已同步': 'Cloud save synced',
    '雲端備份暫停': 'Cloud backup paused',
    '已登入': 'Signed in',
    '玩家': 'Player',
    '狀態(可觀看寵物成長資訊)': 'Status (view pet growth)',
    '互動(餵食或撫摸寵物)': 'Care (feed or pet)',
    '談心(根據喜好改變寵物特性)': 'Heart Talk (shape pet traits)',
    '聯盟大會(參加錦標賽)': 'League (enter tournament)',
    '冒險(帶寵物野外探險與捕捉)': 'Adventure (explore and capture)',
    '連線(與陌生寵物對抗、交流)': 'Connect (battle and interact)',
    '圖鑑(查看已收集的像素怪獸)': 'Dex (view collected monsters)',
    '背包(裝著戰利品與寵物的回憶)': 'Bag (loot and memories)',
    '狀態': 'Status',
    '互動': 'Care',
    '談心': 'Talk',
    '聯盟大會': 'League',
    '冒險': 'Adventure',
    '連線': 'Connect',
    '圖鑑': 'Dex',
    '背包': 'Bag',
    '確定': 'Confirm',
    '取消': 'Cancel',
    '返回': 'Back',
    '關閉': 'Close',
    '下一頁': 'Next',
    '上一頁': 'Prev',
    '讀信': 'Read Letter',
    '回信': 'Reply',
    '送出': 'Send',
    '重新開始': 'Restart',
    '重製生命': 'Reset Life',
    '指導手冊': 'Guidebook',
    '怪獸來信': 'Monster Letter',
    '像素怪獸': 'Pixel Monster',
    '寫一封回信給牠': 'Write a reply',
    '例如：今天也一起加油，晚點我會再來看你。': 'Example: Let us do our best today. I will come back later.',
    '不回覆': 'No Reply',
    '寄出回信': 'Send Reply',
    'B 寫回信': 'B Reply',
    'B 下一句': 'B Next',
    '繼續': 'Continue',
    'B 寄出　C 關閉': 'B Send  C Close',
    '準備寄出': 'Ready to send',
    '空白將略過': 'Blank replies are skipped',
    '技能欄位': 'Skill Slots',
    '狀態資訊': 'Status Info',
    '[B] 狀態': '[B] Status',
    '[B] 技能': '[B] Skills',
    '[C] 關閉': '[C] Close',
    '屬性': 'Type',
    '性格': 'Nature',
    '飽食度': 'Fullness',
    '心情度': 'Mood',
    '羈絆值': 'Bond',
    '生命': 'HP',
    '攻擊': 'Attack',
    '防禦': 'Defense',
    '速度': 'Speed',
    '等級': 'Level',
    '戰鬥力': 'Power',
    '天賦': 'Trait',
    '加成': 'Bonus',
    '代價': 'Drawback',
    '尚未分化': 'Undeveloped',
    '尚未覺醒': 'Not awakened',
    '尚未獲得特殊加成': 'No special bonus yet',
    '尚未獲得特殊代價': 'No special drawback yet',
    '目前技能': 'Current Skills',
    '空技能欄': 'Empty Skill Slot',
    '威力': 'Power',
    '命中': 'Accuracy',
    '能力': 'Stat',
    '變化': 'Change',
    '原生異常': 'Native ailment',
    '附魔': 'Enchantment',
    '無': 'None',
    '無附魔': 'No enchantment',
    '[B] 返回狀態　[C] 關閉': '[B] Back to Status  [C] Close',
    '我的背包': 'My Bag',
    '物品清單': 'Item List',
    '未知同伴': 'Unknown Partner',
    '正在使用...': 'Using...',
    '[B] 確認使用': '[B] Use',
    '背包目前是空的': 'Your bag is empty',
    '[A] 下一個  [B] 使用  [C] 關閉': '[A] Next  [B] Use  [C] Close',
    '普': 'Normal',
    '火': 'Fire',
    '水': 'Water',
    '草': 'Grass',
    '毒': 'Poison',
    '飛': 'Flying',
    '蟲': 'Bug',
    '岩': 'Rock',
    '鬼': 'Ghost',
    '燒': 'Burn',
    '麻': 'Para',
    '混': 'Conf',
    '吸': 'Drain',
    '縛': 'Bind',
    '凍': 'Freeze',
    '眠': 'Sleep',
    '血': 'Drain',
    '準': 'Aim',
    '先': 'First',
};

const PARTIAL_TRANSLATIONS = [
    [/^已登入:\s*/u, 'Signed in: '],
    [/^雲端：/u, 'Cloud: '],
    [/^本機：/u, 'Local: '],
    [/^成功連動帳號:\s*/u, 'Account linked: '],
    [/^登入成功:\s*/u, 'Login successful: '],
    [/^雲端讀取錯誤:\s*/u, 'Cloud read error: '],
    [/^選擇：/u, 'Choice: '],
    [/^紀錄：/u, 'Record: '],
];

const REGEX_TRANSLATIONS = [
    [/^進化方向：\n(.+)$/su, (_, body) => `Evolution Path:\n${body.split('\n').map(line => translateText(line, LANGUAGES.en)).join('\n')}`],
    [/^(.+)：無特殊條件$/u, (_, name) => `${translateText(name, LANGUAGES.en)}: No special requirements`],
    [/^(.+) \(無特殊條件\)$/u, (_, name) => `${translateText(name, LANGUAGES.en)} (No special requirements)`],
    [/^(.+) \(無條件進化\)$/u, (_, name) => `${translateText(name, LANGUAGES.en)} (Evolves without extra requirements)`],
    [/^(.+) \(其餘條件\)$/u, (_, name) => `${translateText(name, LANGUAGES.en)} (Other requirements)`],
    [/^(.+) \(心情、飽食度 >= 50\)$/u, (_, name) => `${translateText(name, LANGUAGES.en)} (Mood and Fullness >= 50)`],
    [/^(.+) \(溫柔\/理性\)$/u, (_, name) => `${translateText(name, LANGUAGES.en)} (Gentle / Rational)`],
    [/^(.+) \(熱血\/無俚頭\)$/u, (_, name) => `${translateText(name, LANGUAGES.en)} (Passionate / Silly)`],
    [/^(.+) \(熱血\/執著\)$/u, (_, name) => `${translateText(name, LANGUAGES.en)} (Passionate / Stubborn)`],
    [/^(.+) \(固執\/無俚頭\)$/u, (_, name) => `${translateText(name, LANGUAGES.en)} (Stubborn / Silly)`],
    [/^火系靈魂 \((.+)線\)$/u, (_, name) => `Fire Soul (${translateText(name, LANGUAGES.en)} line)`],
    [/^水系靈魂 \((.+)線\)$/u, (_, name) => `Water Soul (${translateText(name, LANGUAGES.en)} line)`],
    [/^草系靈魂 \((.+)線\)$/u, (_, name) => `Grass Soul (${translateText(name, LANGUAGES.en)} line)`],
    [/^草系靈魂 \((.+)線，熱血\/執著\)$/u, (_, name) => `Grass Soul (${translateText(name, LANGUAGES.en)} line, Passionate / Stubborn)`],
    [/^蟲系靈魂 \((.+)線\)$/u, (_, name) => `Bug Soul (${translateText(name, LANGUAGES.en)} line)`],
    [/^蟲系靈魂 \((.+)線，固執\/無俚頭\)$/u, (_, name) => `Bug Soul (${translateText(name, LANGUAGES.en)} line, Stubborn / Silly)`],
    [/^一般線 ([A-Z]) \((.+)\)$/u, (_, branch, name) => `Normal Line ${branch} (${translateText(name, LANGUAGES.en)})`],
    [/^絆 \+(\d+)！$/u, (_, points) => `Bond +${points}!`],
    [/^我好累，讓我休息 (\d+) 秒再出發吧$/u, (_, seconds) => `I am tired. Let me rest ${seconds} seconds before heading out.`],
    [/^(.+) 想學會 (.+)$/u, (_, name, move) => `${translateText(name, LANGUAGES.en)} wants to learn ${translateText(move, LANGUAGES.en)}.`],
    [/^解鎖了新的圖鑑：(.+)$/u, (_, name) => `New dex entry unlocked: ${translateText(name, LANGUAGES.en)}`],
    [/^經過訓練，(.+)潛能提升了！$/u, (_, stat) => `Training improved ${translateText(stat, LANGUAGES.en)} potential!`],
    [/^特訓成功！(.+)潛能 \+(\d+)$/u, (_, stat, gain) => `Training success! ${translateText(stat, LANGUAGES.en)} potential +${gain}`],
    [/^✨ (.+) 成為了你的新夥伴！$/u, (_, name) => `${translateText(name, LANGUAGES.en)} became your new partner!`],
    [/^(.+)觸發！HP 回到 1，戰鬥繼續。$/u, (_, trait) => `${translateText(trait, LANGUAGES.en)} activated! HP returned to 1. Battle continues.`],
    [/^(.+)結束，傷害倍率回到 100%。$/u, (_, trait) => `${translateText(trait, LANGUAGES.en)} ended. Damage multiplier returned to 100%.`],
    [/^🏆 戰鬥勝利！獲得 (\d+) 點成長。$/u, (_, gain) => `Battle won! Gained ${gain} growth.`],
    [/^戰鬥勝利！獲得 (\d+) 點成長。$/u, (_, gain) => `Battle won! Gained ${gain} growth.`],
    [/^擊敗了精英怪：(.+)$/u, (_, name) => `Defeated elite monster: ${translateText(name, LANGUAGES.en)}`],
    [/^擊敗了野怪：(.+)$/u, (_, name) => `Defeated wild monster: ${translateText(name, LANGUAGES.en)}`],
    [/^🎁 獲得了戰利品：(.+)！$/u, (_, item) => `Obtained loot: ${translateText(item, LANGUAGES.en)}!`],
    [/^✨ 感覺 (.+) 想成為你的夥伴\.\.\.$/u, (_, name) => `It feels like ${translateText(name, LANGUAGES.en)} wants to become your partner...`],
    [/^房間已建立，等待對手輸入房號 (.+) \.\.\.$/u, (_, room) => `Room created. Waiting for opponent to enter code ${room}...`],
    [/^大賽引擎發生錯誤：(.+)$/u, (_, error) => `Tournament engine error: ${error}`],
    [/^冠軍挑戰：排行榜訓練家 (.+) 現身！$/u, (_, name) => `Champion challenge: leaderboard trainer ${name} appears!`],
    [/^(.+) 使出了 \[(.+)\]！$/u, (_, name, move) => `${translateText(name, LANGUAGES.en)} used [${translateText(move, LANGUAGES.en)}]!`],
    [/^(.+) 的招式偏離了目標！$/u, (_, name) => `${translateText(name, LANGUAGES.en)}'s move missed the target!`],
    [/^【附魔失敗】技能 \[(.+)\] 是輔助類技能，無法附魔！$/u, (_, move) => `Enchantment failed: [${translateText(move, LANGUAGES.en)}] is a support skill and cannot be enchanted!`],
    [/^【機率已達上限】技能 \[(.+)\] 的 (.+) 已達 100% 上限！$/u, (_, move, effect) => `Chance cap reached: [${translateText(move, LANGUAGES.en)}] ${translateText(effect, LANGUAGES.en)} is already at 100%!`],
    [/^【強化次數上限】技能 \[(.+)\] 已達強化上限 \(10\/10\)！$/u, (_, move) => `Upgrade cap reached: [${translateText(move, LANGUAGES.en)}] is already at 10/10!`],
    [/^冠軍獎勵：\[(.+)\] 獲得了 (.+)！\((\d+)\/10\)$/u, (_, move, effect, count) => `Champion reward: [${translateText(move, LANGUAGES.en)}] gained ${translateText(effect, LANGUAGES.en)}! (${count}/10)`],
    [/^(.+) \/ 威力:(.+) \/ 命中:(.+)$/u, (_, type, power, accuracy) => `${translateText(type, LANGUAGES.en)} / Power:${power} / Accuracy:${accuracy}`],
];

const ENGLISH_NAME_OVERRIDES = {
    cross_defense: 'Cross Defense',
    reflect_shield: 'Reflect Shield',
    guardian_shield: 'Guardian Shield',
    swords_dance: 'Battle Dance',
    double_team: 'Shadow Clone',
    water_gun: 'Water Gun',
    vine_whip: 'Vine Whip',
    quick_attack: 'Quick Attack',
    extreme_speed: 'Extreme Speed',
    fake_out: 'Fake Out',
    hyper_beam: 'Hyper Beam',
    giga_impact: 'Giga Impact',
    last_resort: 'Last Resort',
    skull_bash: 'Skull Bash',
    mega_kick: 'Mega Kick',
    double_edge: 'Double-Edge',
    brave_heart: 'Brave Heart',
    steady_body: 'Steady Body',
    quick_sense: 'Quick Sense',
    kind_soul: 'Kind Soul',
    late_bloomer: 'Late Bloomer',
    eight_gates: 'Eight Gates',
    feign_death: 'Feign Death',
    absolute_defense: 'Absolute Defense',
    sun_child: 'Child of the Sun',
    rain_doll: 'Rain Doll',
    magician: 'Magician',
};

const toEnglishTitle = (id = '') => {
    const override = ENGLISH_NAME_OVERRIDES[id];
    if (override) return override;
    return String(id)
        .split(/[_-]+/u)
        .filter(Boolean)
        .map(part => part.charAt(0).toUpperCase() + part.slice(1))
        .join(' ');
};

const DATA_NAME_TRANSLATIONS = {
    ...Object.fromEntries(
        Object.values(SKILL_DATABASE || {})
            .filter(move => move?.name && move?.id)
            .map(move => [move.name, toEnglishTitle(move.id)])
    ),
    ...Object.fromEntries(
        (MONSTER_TRAITS || [])
            .filter(trait => trait?.name && trait?.id)
            .map(trait => [trait.name, toEnglishTitle(trait.id)])
    ),
};

const PHRASE_TRANSLATIONS = {
    '像素怪獸': 'Pixel Monster',
    '怪獸': 'Monster',
    '寵物': 'Pet',
    '主人': 'Trainer',
    '夥伴': 'Partner',
    '同伴': 'Partner',
    '訓練家': 'Trainer',
    '排行榜': 'Leaderboard',
    '大賽': 'Tournament',
    '聯盟': 'League',
    '冠軍': 'Champion',
    '挑戰': 'Challenge',
    '冒險': 'Adventure',
    '戰鬥': 'Battle',
    '對戰': 'Battle',
    '勝利': 'Victory',
    '戰敗': 'Defeat',
    '逃跑': 'Escape',
    '野怪': 'Wild monster',
    '精英怪': 'Elite monster',
    '技能': 'Skill',
    '招式': 'Move',
    '輔助': 'Support',
    '附魔': 'Enchantment',
    '強化': 'Upgrade',
    '機率': 'Chance',
    '上限': 'Cap',
    '異常': 'Ailment',
    '燒傷': 'Burn',
    '麻痺': 'Paralysis',
    '中毒': 'Poison',
    '混亂': 'Confusion',
    '寄生': 'Leech',
    '束縛': 'Bind',
    '冰凍': 'Freeze',
    '睡眠': 'Sleep',
    '吸血': 'Life steal',
    '命中率': 'Accuracy',
    '優先度': 'Priority',
    '傷害': 'Damage',
    '體力': 'HP',
    '生命': 'HP',
    '攻擊': 'Attack',
    '防禦': 'Defense',
    '速度': 'Speed',
    '等級': 'Level',
    '成長': 'Growth',
    '潛能': 'Potential',
    '努力值': 'Effort',
    '狀態': 'Status',
    '屬性': 'Type',
    '圖鑑': 'Dex',
    '背包': 'Bag',
    '物品': 'Item',
    '戰利品': 'Loot',
    '回憶膠囊': 'Memory Capsule',
    '飯糰': 'Rice Ball',
    '本機': 'Local',
    '雲端': 'Cloud',
    '存檔': 'Save',
    '同步': 'Sync',
    '登入': 'Login',
    '連線': 'Connection',
    '房間': 'Room',
    '房號': 'Room code',
    '對手': 'Opponent',
    '讀取': 'Read',
    '失敗': 'Failed',
    '成功': 'Success',
    '錯誤': 'Error',
    '逾時': 'Timed out',
    '建立': 'Create',
    '輸入': 'Enter',
    '選擇': 'Choice',
    '確認': 'Confirm',
    '取消': 'Cancel',
    '關閉': 'Close',
    '返回': 'Back',
    '下一個': 'Next',
    '使用': 'Use',
    '目前': 'Current',
    '清單': 'List',
    '空的': 'Empty',
    '未知': 'Unknown',
    '未命名': 'Unnamed',
    '您的怪獸': 'Your Monster',
    '你的回信我讀完了': 'I finished reading your reply',
    '看到回信時我停下來想了一下': 'When I saw your reply, I stopped and thought for a while',
    '那封回信我看了不只一遍': 'I read that reply more than once',
    '我沒有馬上回你是因為我想把答案說得更確定一點': 'I did not answer right away because I wanted to be more certain',
    '那句話我記住了接下來會用行動證明我真的聽進去了': 'I remembered those words and will show you through my actions',
    '那句話讓我重新整理今天要做的事也整理了心情': 'Those words helped me sort out both my day and my feelings',
    '我把它想了好幾遍發現那不是普通的一句話': 'I thought about it many times and realized it was not ordinary',
    '您': 'You',
    '我': 'I',
    '牠': 'it',
    '你': 'you',
    '今天': 'today',
    '明天': 'tomorrow',
    '晚上': 'tonight',
    '早上': 'morning',
    '天氣': 'weather',
    '新聞': 'news',
    '歷史': 'history',
    '星象': 'astrology',
    '塔羅': 'tarot',
    '來信': 'letter',
    '回信': 'reply',
    '寄出': 'send',
    '閱讀': 'read',
    '心情': 'mood',
    '羈絆': 'bond',
    '飽食': 'fullness',
    '個性': 'personality',
    '溫柔': 'Gentle',
    '執著': 'Stubborn',
    '熱血': 'Passionate',
    '搞怪': 'Playful',
    '冷靜': 'Calm',
    '理性': 'Rational',
    '無俚頭': 'Silly',
    '火系': 'Fire',
    '水系': 'Water',
    '草系': 'Grass',
    '蟲系': 'Bug',
    '岩系': 'Rock',
    '飛行系': 'Flying',
    '幽靈系': 'Ghost',
    '普通系': 'Normal',
    '本地': 'Local',
    '本地存檔': 'Local Save',
    '優先級最高': 'Highest priority',
    '如果': 'if',
    '在播報': 'while broadcasting',
    '餵食了怪獸': 'fed the monster',
    '野生': 'wild',
    '直接': 'directly',
    '嚴格檢查': 'strict check',
    '紀錄': 'record',
    '第': 'No.',
    '感人': 'moving',
    '提示': 'prompt',
    '野外': 'wild',
    '動態': 'animated',
    '靜態': 'static',
    '想學會': 'wants to learn',
    '技能欄': 'skill slots',
    '選取': 'select',
    '交換': 'swap',
    '靈魂共鳴': 'Soul Resonance',
    '精力充沛': 'Full of Energy',
    '活力': 'energy',
    '活力噴泉': 'Energy Fountain',
    '休息茶': 'Rest Tea',
    '小點心': 'Snack',
    '神秘加護': 'Mystic Blessing',
    '鏡面命運': 'Mirror Fate',
    '替換命運': 'Swap Fate',
    '活力命運': 'Energy Fate',
    '體力命運': 'HP Fate',
    '回聲命運': 'Echo Fate',
    '情緒命運': 'Emotion Fate',
    '收藏命運': 'Collection Fate',
    '堆疊邏輯': 'Stacking Logic',
    '允許堆疊': 'Allow stacking',
    '渲染': 'render',
    '探索': 'explore',
    '探索進度': 'Exploration Progress',
    '能量': 'energy',
    '舞台': 'stage',
    '介面': 'interface',
    '命運卡': 'fate card',
    '接受': 'accept',
    '能力覺醒': 'Ability Awakening',
    '覺醒加護': 'Awakening Blessing',
    '累積': 'accumulate',
    '剩餘': 'remaining',
    '傾向': 'tendency',
    '性格': 'Nature',
    '決賽': 'Finals',
    '輔助技': 'Support Skill',
    '背景': 'background',
    '遮罩': 'overlay',
    '視窗': 'window',
    '標題列': 'title bar',
    '教學': 'tutorial',
    '手冊': 'manual',
    '快速': 'quick',
    '提問': 'question',
    '進化鏈': 'evolution chain',
    '幼年期': 'child stage',
    '小雞獸線': 'Chickmon line',
    '石精靈線': 'Stone spirit line',
    '基礎': 'base',
    '其餘': 'other',
    '活力飯糰': 'Energy Rice Ball',
    '覺醒之核': 'Awakening Core',
    '奇異糖果': 'Rare Candy',
    '堅硬秘笈書': 'Hard Guard Manual',
    '堅硬防守': 'Hard Guard',
    '影子分身術': 'Shadow Clone',
    '反射盾': 'Reflect Shield',
    '技能轉換器': 'Skill Converter',
    '永不消耗': 'Never consumed',
    '撞擊': 'Tackle',
    '交流': 'interact',
    '名稱': 'name',
    '陣列': 'array',
    '今天練很多': 'trained a lot today',
    '跟你在一起': 'being with you',
    '你也是': 'you too',
    '有你陪著': 'with you by my side',
    '嘿': 'hey',
    '你不知道吧': 'you probably did not know',
    '一起加油吧': 'let us do our best',
    '聽著下雨聲': 'listening to the rain',
    '感覺很平靜': 'feels very calm',
    '肚子好餓喔': 'my belly is so hungry',
    '晚餐吃啥': 'what is for dinner',
    '看著營火': 'watching the campfire',
    '聽柴火聲音': 'listening to the crackling fire',
    '不管啦': 'whatever',
    '絕對不退': 'never back down',
    '冷靜分析': 'calm analysis',
    '把話說清楚': 'say it clearly',
    '氣到冒火': 'angry enough to burst into flames',
    '死也要道歉': 'apologize no matter what',
    '家': 'home',
    '有很多植物': 'has many plants',
    '空氣很好': 'the air is very nice',
    '欄位說明': 'field description',
    '晶片獸': 'Chipmon',
    '火星寶寶': 'Mars Baby',
    '火星獸': 'Marsmon',
    '火星摔角人': 'Mars Wrestler',
    '泡泡娃': 'Bubble Doll',
    '吹泡蠑螈': 'Bubble Salamander',
    '大師蠑螈': 'Master Salamander',
    '守護龍仔': 'Guardian Drake',
    '守護龍獸': 'Guardian Dragon',
    '喵星人': 'Meow Martian',
    '喵星特務X': 'Meow Agent X',
    '綿綿獸': 'Fluffmon',
    '甜點獸': 'Dessertmon',
    '草莓蛋糕獸': 'Strawberry Cakemon',
    '熱血芽獸': 'Hot-Blooded Sproutmon',
    '棘藤猴子': 'Thornvine Monkey',
    '森拳金剛': 'Forest Fist Kong',
    '藍領蜂': 'Blue-Collar Bee',
    '社畜蜂兵': 'Worker Bee Soldier',
    '女王蜂': 'Queen Bee',
    '小角幼甲': 'Little Horn Larva',
    '鐵角甲士': 'Ironhorn Beetle',
    '聖甲戰蟲': 'Sacred Beetle',
    '黑德魯': 'Black Druid',
    '野性德魯': 'Wild Druid',
    '王者德魯': 'Druid King',
    '伊麗莎': 'Eliza',
    '麗莎狐': 'Lisa Fox',
    '女皇莎白': 'Queen Elizabeth',
    '幽燭燭': 'Ghost Candle',
    '鍋爐燭燭': 'Boiler Candle',
    '幽靈女王': 'Ghost Queen',
    '螢手噗': 'Glowpuff',
    '露璃': 'Luli',
    '小雞獸': 'Chickmon',
    '捲尾麻雀': 'Curlytail Sparrow',
    'US老鷹獸': 'US Eaglemon',
    '石精靈': 'Stone Spirit',
    '岩石巨兵': 'Rock Giant',
    '石像魔': 'Gargoyle',
    '普通': 'Normal',
    '火': 'Fire',
    '水': 'Water',
    '草': 'Grass',
    '毒': 'Poison',
    '飛': 'Flying',
    '蟲': 'Bug',
    '岩': 'Rock',
    '鬼': 'Ghost',
    '電': 'Electric',
    '冰': 'Ice',
    '鬥': 'Fighting',
    '地': 'Ground',
    '超': 'Psychic',
    '龍': 'Dragon',
    '鋼': 'Steel',
    '惡': 'Dark',
    '妖': 'Fairy',
    '與': ' and ',
};

const TRANSLATION_GLOSSARY = {
    ...DATA_NAME_TRANSLATIONS,
    ...PHRASE_TRANSLATIONS,
};

const REPLACEMENT_ORDER = Object.keys(TRANSLATION_GLOSSARY).sort((a, b) => b.length - a.length);

const CHAR_TRANSLATIONS = {
    '一': 'one',
    '二': 'two',
    '三': 'three',
    '四': 'four',
    '五': 'five',
    '六': 'six',
    '七': 'seven',
    '八': 'eight',
    '九': 'nine',
    '十': 'ten',
    '上': 'up',
    '下': 'down',
    '左': 'left',
    '右': 'right',
    '中': 'middle',
    '底': 'bottom',
    '層': 'layer',
    '頂': 'top',
    '部': 'part',
    '文': 'text',
    '字': 'word',
    '按': 'press',
    '鍵': 'key',
    '任': 'any',
    '意': 'meaning',
    '開': 'open',
    '始': 'start',
    '關': 'close',
    '閉': 'close',
    '返': 'return',
    '回': 'return',
    '入': 'enter',
    '出': 'out',
    '來': 'come',
    '去': 'go',
    '離': 'leave',
    '等': 'wait',
    '待': 'wait',
    '稍': 'later',
    '候': 'wait',
    '再': 'again',
    '先': 'first',
    '後': 'after',
    '前': 'before',
    '今': 'today',
    '明': 'tomorrow',
    '昨': 'yesterday',
    '日': 'day',
    '期': 'period',
    '時': 'time',
    '間': 'time',
    '秒': 'second',
    '週': 'week',
    '月': 'month',
    '年': 'year',
    '早': 'morning',
    '晚': 'night',
    '全': 'all',
    '個': 'count',
    '項': 'item',
    '封': 'letter',
    '筆': 'entry',
    '點': 'point',
    '級': 'level',
    '數': 'number',
    '量': 'amount',
    '值': 'value',
    '率': 'rate',
    '源': 'source',
    '因': 'reason',
    '原': 'original',
    '格': 'format',
    '式': 'style',
    '版': 'version',
    '型': 'type',
    '類': 'class',
    '清': 'clear',
    '除': 'remove',
    '新': 'new',
    '增': 'add',
    '建': 'build',
    '立': 'create',
    '產': 'generate',
    '生': 'life',
    '自': 'self',
    '動': 'auto',
    '重': 'reset',
    '置': 'set',
    '恢': 'restore',
    '復': 'restore',
    '預': 'preset',
    '設': 'setting',
    '鎖': 'lock',
    '定': 'fixed',
    '解': 'unlock',
    '未': 'not',
    '已': 'already',
    '讀': 'read',
    '寫': 'write',
    '寄': 'send',
    '信': 'letter',
    '話': 'talk',
    '題': 'topic',
    '聞': 'news',
    '史': 'history',
    '星': 'star',
    '塔': 'tower',
    '羅': 'tarot',
    '氣': 'energy',
    '天': 'sky',
    '溫': 'temperature',
    '度': 'degree',
    '雨': 'rain',
    '雪': 'snow',
    '風': 'wind',
    '陰': 'cloudy',
    '炎': 'hot',
    '熱': 'hot',
    '寒': 'cold',
    '冷': 'cold',
    '舒': 'comfortable',
    '適': 'comfortable',
    '暴': 'storm',
    '未': 'not',
    '來': 'future',
    '體': 'body',
    '感': 'feel',
    '效': 'effect',
    '能': 'ability',
    '最': 'most',
    '佳': 'best',
    '化': 'ize',
    '資': 'data',
    '料': 'data',
    '遷': 'migrate',
    '移': 'move',
    '初': 'initial',
    '其': 'other',
    '他': 'other',
    '觸': 'trigger',
    '發': 'trigger',
    '淡': 'fade',
    '秒': 'second',
    '週': 'cycle',
    '參': 'join',
    '併': 'merge',
    '過': 'over',
    '舊': 'old',
    '跨': 'cross',
    '越': 'over',
    '絆': 'bond',
    '經': 'after',
    '訓': 'train',
    '練': 'train',
    '提': 'raise',
    '升': 'raise',
    '了': '',
    '特': 'special',
    '繼': 'continue',
    '續': 'continue',
    '讓': 'let',
    '休': 'rest',
    '息': 'rest',
    '吧': '',
    '事': 'event',
    '採': 'gather',
    '集': 'gather',
    '獲': 'obtain',
    '得': 'get',
    '它': 'it',
    '防': 'prevent',
    '止': 'stop',
    '穿': 'pass',
    '透': 'through',
    '吼': 'roar',
    '優': 'priority',
    '限': 'limit',
    '制': 'control',
    '指': 'point',
    '向': 'to',
    '放': 'give',
    '棄': 'up',
    '翻': 'turn',
    '超': 'over',
    '真': 'really',
    '好': 'good',
    '吃': 'eat',
    '餵': 'feed',
    '肚': 'belly',
    '子': '',
    '太': 'too',
    '餓': 'hungry',
    '心': 'heart',
    '親': 'close',
    '密': 'intimate',
    '分': 'branch',
    '進': 'advance',
    '成': 'become',
    '線': 'line',
    '完': 'complete',
    '封': 'seal',
    '保': 'keep',
    '強': 'strong',
    '壯': 'strong',
    '狂': 'wild',
    '疾': 'swift',
    '精': 'elite',
    '銳': 'elite',
    '跳': 'jump',
    '重': 'important',
    '降': 'fall',
    '臨': 'arrive',
    '帶': 'bring',
    '著': '',
    '撿': 'pick',
    '獎': 'reward',
    '勵': 'encourage',
    '單': 'single',
    '修': 'fix',
    '正': 'correct',
    '用': 'use',
    '湧': 'surge',
    '現': 'appear',
    '替': 'replace',
    '換': 'change',
    '搭': 'partner',
    '檔': 'partner',
    '沒': 'no',
    '遺': 'regret',
    '憾': 'regret',
    '傳': 'inherit',
    '承': 'inherit',
    '幽': 'ghost',
    '影': 'shadow',
    '附': 'attach',
    '身': 'body',
    '常': 'normal',
    '啟': 'start',
    '模': 'mode',
    '確': 'confirm',
    '終': 'end',
    '談': 'talk',
    '互': 'interact',
    '溫': 'gentle',
    '和': 'and',
    '執': 'execute',
    '行': 'run',
    '帳': 'account',
    '號': 'number',
    '登': 'login',
    '登': 'login',
    '登': 'login',
    '登': 'login',
    '登': 'login',
    '太': 'sun',
    '陽': 'sun',
    '之': 'of',
    '娃': 'doll',
    '嚴': 'strict',
    '掃': 'sweep',
    '蕩': 'sweep',
    '決': 'duel',
    '卻': 'cool',
    '準': 'ready',
    '備': 'ready',
    '就': 'ready',
    '緒': 'state',
    '宇': 'space',
    '宙': 'space',
    '廳': 'hall',
    '密': 'password',
    '碼': 'code',
    '況': 'condition',
    '上': 'online',
    '球': 'global',
    '血': 'blood',
    '條': 'bar',
    '區': 'area',
    '域': 'area',
    '路': 'path',
    '加': 'join',
    '否': 'No',
    '是': 'Yes',
    '偵': 'debug',
    '錯': 'error',
    '控': 'control',
    '器': 'device',
    '整': 'adjust',
    '無': 'none',
    '必': 'must',
    '遇': 'encounter',
    '隨': 'random',
    '機': 'chance',
    '蛋': 'egg',
    '白': 'white',
    '粉': 'powder',
    '核': 'core',
    '糖': 'candy',
    '果': 'fruit',
    '煉': 'forge',
    '獄': 'inferno',
    '炮': 'cannon',
    '測': 'test',
    '試': 'test',
    '外': 'external',
    '內': 'internal',
    '全': 'all',
    '如': 'such as',
    '不': 'not',
    '合': 'combine',
    '地': 'local',
    '到': 'to',
    '累': 'tired',
    '為': 'as',
    '件': 'event',
    '結': 'end',
    '束': 'end',
    '覺': 'feel',
    '抖': 'shake',
    '且': 'and',
    '抓': 'catch',
    '播': 'broadcast',
    '報': 'report',
    '的': '',
    '抽': 'draw',
    '籤': 'lot',
    '每': 'each',
    '啦': '',
    '打': 'open',
    '即': 'immediate',
    '直': 'direct',
    '法': 'able',
    '憶': 'memory',
    '呆': 'guard',
    '有': 'have',
    '謝': 'thanks',
    '請': 'please',
    '要': 'want',
    '嗎': '',
    '系': 'system',
    '統': 'system',
    '鈕': 'button',
    '普': 'Normal',
    '查': 'check',
    '對': 'versus',
    '狀': 'status',
    '大': 'big',
    '固': 'firm',
    '磁': 'magnetic',
    '尚': 'still',
    '覆': 'cover',
    '蓋': 'cover',
    '實': 'actual',
    '際': 'actual',
    '賦': 'talent',
    '切': 'switch',
    '益': 'benefit',
    '代': 'cost',
    '價': 'price',
    '勢': 'advantage',
    '選': 'select',
    '像': 'like',
    '守': 'guard',
    '護': 'protect',
    '者': 'one',
    '盾': 'shield',
    '次': 'times',
    '空': 'empty',
    '命': 'life',
    '套': 'apply',
    '當': 'current',
    '總': 'total',
    '計': 'count',
    '想': 'want',
    '記': 'record',
    '錄': 'record',
    '顧': 'review',
    '婉': 'graceful',
    '嘴': 'mouth',
    '硬': 'stubborn',
    '澎': 'surging',
    '湃': 'surging',
    '調': 'playful',
    '皮': 'mischief',
    '搗': 'trouble',
    '沉': 'deep',
    '穩': 'steady',
    '隻': 'one',
    '殊': 'special',
    '頁': 'page',
    '主': 'main',
    '只': 'only',
    '願': 'willing',
    '提': 'prompt',
    '擊': 'click',
    '方': 'direction',
    '條': 'condition',
    '靈': 'soul',
    '魂': 'soul',
    '般': 'general',
    '例': 'example',
    '句': 'sentence',
    '起': 'start',
    '語': 'language',
    '言': 'language',
    '靜': 'static',
    '操': 'operation',
    '作': 'action',
    '威': 'power',
    '力': 'power',
    '造': 'cause',
    '攻': 'attack',
    '速': 'speed',
    '滿': 'full',
    '學': 'learn',
    '習': 'learn',
    '變': 'change',
    '完': 'complete',
    '良': 'good',
    '伴': 'partner',
    '觸': 'trigger',
    '降': 'descend',
    '蒐': 'collect',
    '藏': 'store',
    '讀': 'read',
};

const replaceKnownPhrases = (text) => {
    let translated = text;
    REPLACEMENT_ORDER.forEach((phrase) => {
        translated = translated.split(phrase).join(` ${TRANSLATION_GLOSSARY[phrase]} `);
    });
    return translated;
};

const normalizeEnglishPunctuation = (text) => text
    .replace(/：/gu, ': ')
    .replace(/，/gu, ', ')
    .replace(/。/gu, '.')
    .replace(/！/gu, '!')
    .replace(/？/gu, '?')
    .replace(/（/gu, '(')
    .replace(/）/gu, ')')
    .replace(/「/gu, '"')
    .replace(/」/gu, '"')
    .replace(/【/gu, '[')
    .replace(/】/gu, ']')
    .replace(/　/gu, ' ')
    .replace(/\s{2,}/gu, ' ')
    .trim();

const translateUnknownChinese = (match) => {
    const words = [];
    for (const char of match) {
        const translated = CHAR_TRANSLATIONS[char];
        if (translated === '') continue;
        if (translated) {
            words.push(translated);
        }
    }
    return words.join(' ');
};

const removeRemainingChinese = (text, original) => {
    if (!/[\p{Script=Han}]/u.test(text)) return text;

    return text.replace(/[\p{Script=Han}]+/gu, (match) => {
        if (TRANSLATION_GLOSSARY[match]) return TRANSLATION_GLOSSARY[match];
        if (/怪獸|寵物|牠|獸/.test(match)) return 'Monster';
        if (/技能|招式/.test(match)) return 'Skill';
        if (/物品|背包/.test(match)) return 'Item';
        if (/戰|勝|敗/.test(match)) return 'Battle';
        if (/雲|存|登入/.test(match)) return 'Cloud';
        return translateUnknownChinese(match);
    });
};

export const getStoredLanguage = () => {
    try {
        const stored = localStorage.getItem(LANGUAGE_STORAGE_KEY);
        return stored === LANGUAGES.zh ? LANGUAGES.zh : LANGUAGES.en;
    } catch {
        return LANGUAGES.en;
    }
};

export const setStoredLanguage = (language) => {
    const nextLanguage = language === LANGUAGES.en ? LANGUAGES.en : LANGUAGES.zh;
    localStorage.setItem(LANGUAGE_STORAGE_KEY, nextLanguage);
    window.dispatchEvent(new CustomEvent('pixel_monster_language_update', {
        detail: { language: nextLanguage },
    }));
};

export const translateText = (text, language = getStoredLanguage()) => {
    if (language !== LANGUAGES.en || typeof text !== 'string') return text;

    const leading = text.match(/^\s*/u)?.[0] || '';
    const trailing = text.match(/\s*$/u)?.[0] || '';
    let core = text.trim();
    if (!core) return text;

    if (EXACT_TRANSLATIONS[core]) {
        return `${leading}${EXACT_TRANSLATIONS[core]}${trailing}`;
    }

    for (const [pattern, replacement] of REGEX_TRANSLATIONS) {
        if (pattern.test(core)) {
            return `${leading}${core.replace(pattern, replacement)}${trailing}`;
        }
    }

    for (const [pattern, replacement] of PARTIAL_TRANSLATIONS) {
        if (pattern.test(core)) {
            core = core.replace(pattern, replacement);
            break;
        }
    }

    core = replaceKnownPhrases(core);
    core = normalizeEnglishPunctuation(core);
    core = removeRemainingChinese(core, text);

    return `${leading}${core}${trailing}`;
};
